name: AI Node Deployment

on:
  workflow_dispatch:

# جلوگیری از تداخل اجراهای همزمان
concurrency:
  group: ai-node
  cancel-in-progress: true

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: System Deployment
        # در اینجا متغیرها را به محیط اجرای سیستم معرفی می‌کنیم
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          chmod +x ./setup.sh
          ./setup.sh
          
